github:
  is_project_page: false
title: Computational Measurements of Machine Creativity
description: A Workshop for CVPR 2021
# remote_theme: samarsault/texture
# remote_theme: thelehhman/texture
#theme: jekyll-theme-midnight
theme: jekyll-theme-cayman
#theme: jekyll-theme-primer
