github:
  is_project_page: false
title: Computational Measurements of Machine Creativity
description: An Interactive Workshop on Bridging the Gap between Subjective and Computational Measurements of Machine Creativity, for CVPR 2021
# remote_theme: samarsault/texture
# remote_theme: thelehhman/texture
#theme: jekyll-theme-midnight
theme: jekyll-theme-cayman
#theme: jekyll-theme-primer
