github:
  is_project_page: false
title: Computational Measurements of Machine Creativity, CVPR 2021
description: |
  An Interactive Workshop Bridging the Gap between 
  Subjective and Computational Measurements of Machine Creativity
# remote_theme: samarsault/texture
# remote_theme: thelehhman/texture
#theme: jekyll-theme-midnight
theme: jekyll-theme-cayman
#theme: jekyll-theme-primer
